### ISSUE TITLE
How to test the results of self-made datasets?

### ISSUE THREAD

**Issue by Forone-Shijie** [jamycheung/ISSAFE#3]

**Comment by Forone-Shijie** [comment]
Dear author, i want to ask how to make a self-made dataset which suits the code, and how to test the segmentation results of our dataset?

**Comment by jamycheung** [comment]
Hi @Forone-Shijie 
you can try to follow and modify the dataloader to fit your own dataset, for example, the [CityscapesRGBEvent](https://github.com/jamycheung/ISSAFE/blob/master/dataloaders/cityscapes.py#L10).
