### ISSUE TITLE
Some datasets missing

### ISSUE THREAD

**Issue by Forone-Shijie** [jamycheung/ISSAFE#4]
Dear author, there are missing data which you have provided, such as dof in DADA_seg and leftImg8bit_prev in Cityscapes, could you provide the whole dataset?

**Comment by jamycheung** [comment]
Hi @Forone-Shijie 
the DOF dataset is generated by using Farneback's algorithm from the OpenCV. If you are interested in the DOF, you can try different methods. Due to the space limitation, here we just upload the event-based data.
